//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosProducto
    {
        public int Id { get; set; }
        public Nullable<int> servicio_id { get; set; }
        public Nullable<int> producto_id { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
